{{ if eq .Values.db.type "sqlite-pvc" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hub-db-dir
  namespace: {{ .Values.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: hub-storage-{{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: hub
  namespace: {{ .Values.name }}
spec:
  selector:
    name: hub-pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hub-config
  namespace: {{ .Values.name }}
data:
  token.proxy: {{ .Values.token.proxy | quote }}
  {{ if .Values.cull.enabled -}}
  token.culler: {{ .Values.token.culler | quote }}
  {{- end }}

  auth.type: {{ .Values.auth.type | quote }}
  {{ if eq .Values.auth.type "hmac" -}}
  auth.hmac.secret-key: {{ .Values.auth.hmac.secretKey | quote }}
  {{- end }}
  {{ if eq .Values.auth.type "google" -}}
  auth.google.client-id: {{.Values.auth.google.clientId | quote}}
  auth.google.client-secret: {{.Values.auth.google.clientSecret | quote}}
  auth.google.hosted-domain: {{.Values.auth.google.hostedDomain | quote}}
  auth.google.login-service: {{.Values.auth.google.loginService | quote}}
  auth.google.callback-url: {{.Values.auth.google.callbackUrl}}
  {{- end }}
  singleuser.storage.class: single-user-storage-{{ .Values.name }}
  singleuser.storage.capacity: {{.Values.singleuser.storage.capacity | quote }}
  {{ if .Values.singleuser.memory.limit -}}
  singleuser.memory.limit: {{ .Values.singleuser.memory.limit | quote}}
  {{- end }}
  {{ if .Values.singleuser.memory.guarantee -}}
  singleuser.memory.guarantee: {{ .Values.singleuser.memory.guarantee | quote}}
  {{- end }}
  {{ if .Values.singleuser.cpu.limit -}}
  singleuser.cpu.limit: {{ .Values.singleuser.cpu.limit | quote}}
  {{- end }}
  {{ if .Values.singleuser.cpu.guarantee -}}
  singleuser.cpu.guarantee: {{ .Values.singleuser.cpu.guarantee | quote}}
  {{- end }}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hub-deployment
  namespace: {{ .Values.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hub-pod
    spec:
      {{ if eq .Values.db.type "sqlite-pvc" -}}
      volumes:
      - name: hub-db-dir
        persistentVolumeClaim:
          claimName: hub-db-dir
      {{- end }}
      containers:
      - name: hub-container
        image: {{ .Values.hub.image.name }}:{{ .Values.hub.image.tag }}
        {{ if eq .Values.db.type "sqlite-pvc" -}}
        volumeMounts:
          - mountPath: /srv/jupyterhub
            name: hub-db-dir
        {{- end }}
        env:
        - name: SINGLEUSER_STORAGE_CLASS
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: singleuser.storage.class
        - name: SINGLEUSER_STORAGE_CAPACITY
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: singleuser.storage.capacity
        {{ if .Values.singleuser.memory.guarantee -}}
        - name: SINGLEUSER_MEM_GUARANTEE
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: singleuser.memory.limit
        {{- end }}
        {{ if .Values.singleuser.memory.limit -}}
        - name: SINGLEUSER_MEM_LIMIT
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: singleuser.memory.limit
        {{- end }}
        {{ if .Values.singleuser.cpu.guarantee -}}
        - name: SINGLEUSER_CPU_GUARANTEE
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: singleuser.cpu.guarantee
        {{- end }}
        {{ if .Values.singleuser.cpu.limit -}}
        - name: SINGLEUSER_CPU_LIMIT
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: singleuser.cpu.limit
        {{- end }}
        # Put this here directly so hub will restart when we
        # change this
        - name: SINGLEUSER_IMAGE
          value:  "{{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}"
        {{ if .Values.singleuser.mounts -}}
        {{ if .Values.singleuser.mounts.shared -}}
        - name: SHARED_DATA_MOUNTS
          value: "{{ range $key, $value := .Values.singleuser.mounts.shared }}{{$key}}={{$value}};{{end}}"
        {{- end }}
        {{- end }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{ if .Values.cull.enabled -}}
        - name: CULL_JHUB_TOKEN
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: token.culler
        {{- end }}
        - name: CONFIGPROXY_AUTH_TOKEN
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: token.proxy
        - name: HUB_AUTH_TYPE
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.type
        {{ if eq .Values.auth.type "hmac" -}}
        - name: HMAC_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.hmac.secret-key
        {{- end }}
        {{ if eq .Values.auth.type "google" -}}
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.google.client-id
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.google.client-secret
        - name: GOOGLE_OAUTH_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.google.callback-url
        - name: GOOGLE_OAUTH_HOSTED_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.google.hosted-domain
        - name: GOOGLE_OAUTH_LOGIN_SERVICE
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.google.login-service
        {{- end }}
        ports:
          - containerPort: 8081
            name: hub
